[workspace]
    default-members=["."]
    members=[".", "crates/abi", "crates/android", "crates/graphics-vulkan", "crates/jni", "crates/jnivm", "crates/linker"]
    resolver="3"

    [workspace.package]
        edition="2024"
        license="GPL-3.0-or-later"
        version="0.1.2"

[package]
    description="Embeddable Roblox Android runtime for Linux"
    edition.workspace=true
    license.workspace=true
    name="roblox-runtime"
    version.workspace=true

[dependencies]
    roblox-abi={path="crates/abi"}
    roblox-android={path="crates/android"}
    roblox-graphics-vulkan={path="crates/graphics-vulkan"}
    roblox-jni={path="crates/jni"}
    jnivm={path="crates/jnivm"}
    roblox-linker={path="crates/linker"}
    serde_json="1.0.151"

[lints.rust]
    unsafe_code="deny"
    unsafe_op_in_unsafe_fn="deny"

[lints.clippy]
    undocumented_unsafe_blocks="warn"

[profile.release]
    debug=true
